spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp15t0ny324ix0495fo.mysql.rds.aliyuncs.com:3306/chaiquan?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username:
    password:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 80
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql